// A perfectly balanced set of 72 questions.
// Each of the 24 VIA Character Strengths appears exactly 6 times.
const QUESTIONS = [
  // --- Block 1: Questions 1-12 ---
  {id:1, aText:"I carefully map out a plan and consider potential downsides before starting a project.", aStrength:"Prudence", bText:"I feel a deep connection to a purpose that is bigger than myself.", bStrength:"Spirituality"},
  {id:2, aText:"I get the most satisfaction from playing my role well and helping my team achieve a shared goal.", aStrength:"Teamwork", bText:"I love approaching stubborn problems with a fresh, unconventional angle.", bStrength:"Creativity"},
  {id:3, aText:"I dive into activities with gusto and full-body enthusiasm.", aStrength:"Zest", bText:"I enjoy analyzing details and weighing evidence carefully before making a call.", bStrength:"Judgment"},
  {id:4, aText:"I enjoy exploring new ideas or places without a specific goal, just for the sake of discovery.", aStrength:"Curiosity", bText:"I speak up for my beliefs, even when my view is unpopular.", bStrength:"Bravery"},
  {id:5, aText:"I am most fulfilled when offering wise counsel that helps someone see their situation more clearly.", aStrength:"Perspective", bText:"I instinctively look for small ways to be helpful and make someone's day easier.", bStrength:"Kindness"},
  {id:6, aText:"I am comfortable being my authentic self and representing my intentions truthfully.", aStrength:"Honesty", bText:"I often use playful banter and lighthearted jokes to connect with people.", bStrength:"Humor"},
  {id:7, aText:"I believe in giving people second chances after they have made a mistake.", aStrength:"Forgiveness", bText:"I get excited when I can dive into a new subject and figure it out on my own.", bStrength:"Love of Learning"},
  {id:8, aText:"I step up to organize people and resources to keep our plans moving forward.", aStrength:"Leadership", bText:"I prefer not to draw attention to my achievements, letting my work speak for itself.", bStrength:"Humility"},
  {id:9, aText:"I stick with tasks until they’re finished, even when the initial excitement fades.", aStrength:"Perseverance", bText:"I often pause to admire moments of beauty in nature, art, or a person's skill.", bStrength:"Appreciation of Beauty"},
  {id:10, aText:"I’m happiest when I’m nurturing the bonds with the people I care about most.", aStrength:"Love", bText:"I tend to focus on what could go right in the future, even during tough times.", bStrength:"Hope"},
  {id:11, aText:"I can usually sense how others are feeling and adjust my approach to meet their needs.", aStrength:"Social Intelligence", bText:"I make a point to express my thanks to people, even for small gestures of help.", bStrength:"Gratitude"},
  {id:12, aText:"I work to ensure that rules are applied equally to everyone in a group.", aStrength:"Fairness", bText:"I build routines to keep myself disciplined and avoid distractions.", bStrength:"Self-Regulation"},
  
  // --- Block 2: Questions 13-24 ---
  {id:13, aText:"I am good at spotting potential problems or dangers before they happen.", aStrength:"Prudence", bText:"My personal beliefs are a source of strength and comfort for me.", bStrength:"Spirituality"},
  {id:14, aText:"I enjoy collaborating closely with others more than working alone.", aStrength:"Teamwork", bText:"I love tinkering with everyday routines to make them more inventive and effective.", bStrength:"Creativity"},
  {id:15, aText:"I feel most alive when I’m physically active and full of energy.", aStrength:"Zest", bText:"I try to look at issues from all sides before forming an opinion.", bStrength:"Judgment"},
  {id:16, aText:"I love asking 'why?' and 'how?' just to understand things more deeply.", aStrength:"Curiosity", bText:"I confront tough issues head-on instead of waiting for them to resolve themselves.", bStrength:"Bravery"},
  {id:17, aText:"I enjoy helping people find clarity by connecting their problems to a larger context.", aStrength:"Perspective", bText:"I often do small favors to make life easier for the people around me.", bStrength:"Kindness"},
  {id:18, aText:"I stick to my principles even when there’s pressure to bend them.", aStrength:"Honesty", bText:"I love making people laugh and lightening the mood in a tense situation.", bStrength:"Humor"},
  {id:19, aText:"I am able to let go of a grudge when someone genuinely tries to make things right.", aStrength:"Forgiveness", bText:"I relish the process of mastering a new skill just for the challenge of it.", bStrength:"Love of Learning"},
  {id:20, aText:"I naturally take charge to provide direction when a group seems lost or disorganized.", aStrength:"Leadership", bText:"I’m quick to admit when I don’t know something or when someone else is the expert.", bStrength:"Humility"},
  {id:21, aText:"I honor my commitments, even when it requires more effort than I anticipated.", aStrength:"Perseverance", bText:"I feel a sense of wonder when I see exceptional talent or artistry.", bStrength:"Appreciation of Beauty"},
  {id:22, aText:"I invest consistent time and effort into my closest relationships to make them feel valued.", aStrength:"Love", bText:"I stay optimistic and believe that my efforts will lead to a good outcome.", bStrength:"Hope"},
  {id:23, aText:"I am skilled at reading body language and the emotional tone of a room.", aStrength:"Social Intelligence", bText:"I often take time to reflect on the things I’m thankful for, big and small.", bStrength:"Gratitude"},
  {id:24, aText:"I advocate to make sure everyone gets an equal shot at opportunities.", aStrength:"Fairness", bText:"I can stay focused on a task even when there are tempting distractions.", bStrength:"Self-Regulation"},

  // --- Block 3: Questions 25-36 ---
  {id:25, aText:"I always check the details and think about long-term consequences before I act.", aStrength:"Prudence", bText:"I feel my life is guided by a meaningful spiritual or philosophical framework.", bStrength:"Spirituality"},
  {id:26, aText:"I feel a strong sense of belonging and purpose when working on a team project.", aStrength:"Teamwork", bText:"I enjoy coming up with clever and original ways to express ideas.", bStrength:"Creativity"},
  {id:27, aText:"I bring a contagious, high-spirited energy to group activities.", aStrength:"Zest", bText:"I prefer to base my conclusions on solid facts and logical reasoning.", bStrength:"Judgment"},
  {id:28, aText:"I often get lost in online 'rabbit holes,' chasing facts just because I’m fascinated by them.", aStrength:"Curiosity", bText:"I am willing to take a stand for an idea or a person, even if it means facing criticism.", bStrength:"Bravery"},
  {id:29, aText:"I’m good at stepping back from a conflict and seeing the situation with wisdom and clarity.", aStrength:"Perspective", bText:"I feel a natural impulse to comfort someone who is upset or struggling.", bStrength:"Kindness"},
  {id:30, aText:"I believe it's important to be straightforward and transparent in my dealings with others.", aStrength:"Honesty", bText:"I use humor to build bridges and make tense moments more manageable.", bStrength:"Humor"},
  {id:31, aText:"I don't hold on to anger, as I believe forgiveness is healthier for everyone.", aStrength:"Forgiveness", bText:"I love the feeling of deep satisfaction that comes from learning something new.", bStrength:"Love of Learning"},
  {id:32, aText:"I am effective at inspiring a group of people to work together toward a common goal.", aStrength:"Leadership", bText:"I am happy to share credit freely and celebrate the successes of others.", bStrength:"Humility"},
  {id:33, aText:"I push through obstacles and setbacks to see a project through to the end.", aStrength:"Perseverance", bText:"I am deeply moved by things of great beauty, like a piece of music or a sunset.", bStrength:"Appreciation of Beauty"},
  {id:34, aText:"Showing and receiving affection is a core, essential part of my life.", aStrength:"Love", bText:"I encourage others by pointing out the progress we’ve made and the positive future we’re building.", bStrength:"Hope"},
  {id:35, aText:"I can easily tell what another person might be thinking or feeling.", aStrength:"Social Intelligence", bText:"I make it a habit to thank people for their contributions, no matter how small.", bStrength:"Gratitude"},
  {id:36, aText:"My decisions are guided by a strong principle of impartiality and equal treatment for all.", aStrength:"Fairness", bText:"I am good at managing my impulses and sticking to a healthy or productive routine.", bStrength:"Self-Regulation"},
  
  // --- Block 4: Questions 37-48 ---
  {id:37, aText:"I am cautious by nature and prefer to avoid unnecessary risks.", aStrength:"Prudence", bText:"My faith or life philosophy is a central part of who I am.", bStrength:"Spirituality"},
  {id:38, aText:"I reliably do my share of the work in a group to ensure we all succeed together.", aStrength:"Teamwork", bText:"I find joy in brainstorming off-the-wall ideas that challenge conventional thinking.", bStrength:"Creativity"},
  {id:39, aText:"I look forward to each day with excitement and a sense of adventure.", aStrength:"Zest", bText:"I am an objective thinker who can set aside personal feelings to find the truth.", bStrength:"Judgment"},
  {id:40, aText:"I am naturally inquisitive and love to explore unfamiliar subjects or places.", aStrength:"Curiosity", bText:"I don't shy away from challenging a decision when I believe it is wrong.", bStrength:"Bravery"},
  {id:41, aText:"Friends often seek my advice because they trust my ability to see the bigger picture.", aStrength:"Perspective", bText:"I find fulfillment in performing acts of service for others.", bStrength:"Kindness"},
  {id:42, aText:"My actions consistently align with my words; what you see is what you get.", aStrength:"Honesty", bText:"I enjoy finding the irony or absurdity in a situation and sharing it with a smile.", bStrength:"Humor"},
  {id:43, aText:"I find it easy to let go of hurt and give someone who hurt me a fresh start.", aStrength:"Forgiveness", bText:"I get a thrill from researching a topic and becoming an expert in it.", bStrength:"Love of Learning"},
  {id:44, aText:"I enjoy the responsibility of making final decisions that affect a group.", aStrength:"Leadership", bText:"I believe that listening to others is often more important than stating my own accomplishments.", bStrength:"Humility"},
  {id:45, aText:"I am disciplined and diligent, ensuring that I complete what I've started.", aStrength:"Perseverance", bText:"I notice and appreciate the skill and craftsmanship in well-made things.", bStrength:"Appreciation of Beauty"},
  {id:46, aText:"I am fiercely loyal and protective of my close friends and family.", aStrength:"Love", bText:"I hold a confident belief that things will work out for the best.", bStrength:"Hope"},
  {id:47, aText:"I am adept at navigating different social situations and making people feel at ease.", aStrength:"Social Intelligence", bText:"I feel a profound sense of thankfulness for the good people and things in my life.", bStrength:"Gratitude"},
  {id:48, aText:"I speak up when I see rules being applied unevenly or one person being treated unjustly.", aStrength:"Fairness", bText:"I am good at resisting temptation and staying on track with my long-term goals.", bStrength:"Self-Regulation"},
  
  // --- Block 5: Questions 49-60 ---
  {id:49, aText:"I think through my words carefully to avoid saying something I might regret later.", aStrength:"Prudence", bText:"I often find meaning in events that seem random to others.", bStrength:"Spirituality"},
  {id:50, aText:"I am a cooperative and dependable member of any group I join.", aStrength:"Teamwork", bText:"I like to find new, imaginative ways to solve everyday problems.", bStrength:"Creativity"},
  {id:51, aText:"I wake up most days feeling enthusiastic and ready to take on challenges.", aStrength:"Zest", bText:"I am good at breaking down a complex argument to find its logical strengths and weaknesses.", bStrength:"Judgment"},
  {id:52, aText:"I have a wide range of interests and am always open to learning something new.", aStrength:"Curiosity", bText:"I will face a difficult situation or conversation if it's the right thing to do.", bStrength:"Bravery"},
  {id:53, aText:"I can often provide a wise, calming viewpoint when others are panicking.", aStrength:"Perspective", bText:"I go out of my way to be inclusive and make others feel welcome.", bStrength:"Kindness"},
  {id:54, aText:"I present myself genuinely, without pretending to be someone I'm not.", aStrength:"Honesty", bText:"I believe a good laugh can solve many problems.", bStrength:"Humor"},
  {id:55, aText:"When someone apologizes, I am quick to accept and move on from the conflict.", aStrength:"Forgiveness", bText:"I would rather spend a free afternoon learning a new skill than just relaxing.", bStrength:"Love of Learning"},
  {id:56, aText:"I am energized when I can motivate and guide others towards a successful outcome.", aStrength:"Leadership", bText:"I recognize my own limitations and am always willing to learn from others.", bStrength:"Humility"},
  {id:57, aText:"Finishing a difficult project gives me a greater sense of satisfaction than starting a new one.", aStrength:"Perseverance", bText:"I am captivated by displays of excellence, whether in sports, art, or science.", bStrength:"Appreciation of Beauty"},
  {id:58, aText:"I make it a priority to be a steady and reliable source of support for the people I love.", aStrength:"Love", bText:"I have a clear vision for what I want my future to be like.", bStrength:"Hope"},
  {id:59, aText:"I pick up on the subtle social cues that others often miss in a conversation.", aStrength:"Social Intelligence", bText:"I frequently tell people how much I appreciate what they do for me.", bStrength:"Gratitude"},
  {id:60, aText:"I feel a strong internal need to stand up for the underdog and correct injustice.", aStrength:"Fairness", bText:"I maintain emotional control even when I am under significant stress.", bStrength:"Self-Regulation"},
  
  // --- Block 6: Questions 61-72 ---
  {id:61, aText:"I avoid impulsive choices, preferring a deliberate and measured approach.", aStrength:"Prudence", bText:"I believe there is a larger, interconnected pattern to life that goes beyond the surface.", bStrength:"Spirituality"},
  {id:62, aText:"I believe the best results come from putting the team's goals ahead of individual ambition.", aStrength:"Teamwork", bText:"I am known for my original thinking and unique perspectives.", bStrength:"Creativity"},
  {id:63, aText:"I tackle my work and life with a great deal of passion and vitality.", aStrength:"Zest", bText:"I am a rational person who relies on critical thinking to navigate life.", bStrength:"Judgment"},
  {id:64, aText:"I have a hungry mind; I'm always reading or watching things to learn more about the world.", aStrength:"Curiosity", bText:"I am not afraid to take on a challenge, even if the odds of success are low.", bStrength:"Bravery"},
  {id:65, aText:"I have a knack for simplifying complex issues and giving sound, practical advice.", aStrength:"Perspective", bText:"My first instinct when I see someone in need is to find a way to help.", bStrength:"Kindness"},
  {id:66, aText:"Telling the truth is important to me, even when it's inconvenient or awkward.", aStrength:"Honesty", bText:"I enjoy teasing friends playfully and find humor in everyday life.", bStrength:"Humor"},
  {id:67, aText:"I am not one to hold grudges; I prefer to forgive and restore harmony.", aStrength:"Forgiveness", bText:"I enjoy the challenge of mastering complex topics step-by-step.", bStrength:"Love of Learning"},
  {id:68, aText:"I am confident in my ability to lead a team through a difficult project.", aStrength:"Leadership", bText:"I am aware of my own faults and don't see myself as being better than others.", bStrength:"Humility"},
  {id:69, aText:"I am a finisher; I have the grit to see things through to the very end.", aStrength:"Perseverance", bText:"I take time to notice and enjoy the beautiful details in my surroundings.", bStrength:"Appreciation of Beauty"},
  {id:70, aText:"Being able to love and be loved is what gives my life its deepest meaning.", aStrength:"Love", bText:"Even when things go wrong, I hold on to the belief that a positive outcome is possible.", bStrength:"Hope"},
  {id:71, aText:"I am tuned in to the emotional dynamics of a group and can mediate conflicts effectively.", aStrength:"Social Intelligence", bText:"When something good happens to me, I feel a strong sense of gratitude.", bStrength:"Gratitude"},
  {id:72, aText:"I am passionate about making sure systems and people operate in a just and equitable way.", aStrength:"Fairness", bText:"I have strong self-control and can delay gratification to achieve a future goal.", bStrength:"Self-Regulation"}
];